# Change these first
owner: dotsi # Your GitHub organization or username, where this repository lives
repo: bitamiuptime # The name of this repository

sites:
  - name: Be-terna
    url: https://www.be-terna.com/
  - name: Adacta
    url: https://www.adacta-fintech.com/
  - name: Spica.com
    url: https://www.spica.com/
  - name: Spica.si
    url: https://www.spica.si/
  - name: Allhours.com
    url: https://www.allhours.com/    
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
   baseUrl: /bitamiuptime
  logoUrl: https://www.bitami.si/sites/5059f8f47b06812d93000002/theme/images/bitami-logo-alien-b.png
  name: Bitami Sites Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
